/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import net.proteanit.sql.DbUtils;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author ziri
 */
public class db_admin extends javax.swing.JFrame {

    static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";  
   static final String DB_URL = "jdbc:mysql://localhost/example";
    
    //  Database credentials
   static final String USER = "root";
   static final String PASS = "";
   Connection conn=null;
   ResultSet rs=null;
   PreparedStatement pst= null;
    
   
   public void UpdatejTable2(){
      String sql="select Username, Password from admin";
      try{
          Class.forName("com.mysql.jdbc.Driver");
          conn =(Connection) DriverManager.getConnection(DB_URL,USER,PASS);
          pst=conn.prepareStatement(sql);
          rs=pst.executeQuery();
          jTable2.setModel(DbUtils.resultSetToTableModel(rs));
      }catch(Exception e){
          JOptionPane.showMessageDialog(null, e);
      }
      
      
   }
    /**
     * Creates new form db_admin
     */
    public db_admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        save = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administrator DataBase Maintenance");
        setPreferredSize(new java.awt.Dimension(600, 450));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 255, 102));
        jLabel1.setText("Username");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 36, 65, -1));

        jLabel2.setBackground(new java.awt.Color(204, 255, 102));
        jLabel2.setText("password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 67, 65, 13));

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 33, 138, -1));
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 63, 138, -1));

        save.setBackground(new java.awt.Color(204, 255, 102));
        save.setText("Save");
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMouseClicked(evt);
            }
        });
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 93, 73, -1));

        update.setBackground(new java.awt.Color(204, 255, 102));
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 123, 73, -1));

        delete.setBackground(new java.awt.Color(204, 255, 102));
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 153, 73, -1));

        jButton1.setBackground(new java.awt.Color(204, 255, 102));
        jButton1.setText("main");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 223, 73, -1));

        jLabel4.setBackground(new java.awt.Color(204, 255, 102));
        jLabel4.setText("Administrators");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 13, 120, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Username", "Password"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 33, 310, 330));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2013-12-05.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 600, 450));

        jMenu1.setText("       <<    Users maintenance");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseClicked
        String sql="Select * from admin where Username=? and Password=?";
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn =(Connection) DriverManager.getConnection(DB_URL,USER,PASS);
            pst=conn.prepareStatement(sql);
            pst.setString(1,username.getText() );
            pst.setString(2,password.getText() );
            pst.execute();
            JOptionPane.showMessageDialog(null, "Saved");

        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_saveMouseClicked

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed

        String sql="insert into admin(Username, Password) values (?,? )";
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn =(Connection) DriverManager.getConnection(DB_URL,USER,PASS);
            pst=conn.prepareStatement(sql);
            pst.setString(1,username.getText() );
            pst.setString(2,password.getText() );
            pst.execute();
            JOptionPane.showMessageDialog(null, "Saved");

            username.setText("");
            password.setText("");

        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        } // TODO add your handling code here:

        
        UpdatejTable2();
    }//GEN-LAST:event_saveActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        String sql="update admin set Password=? where Username=? ";
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn =(Connection) DriverManager.getConnection(DB_URL,USER,PASS);
            pst=conn.prepareStatement(sql);
            pst.setString(1,password.getText() );
            pst.setString(2,username.getText() );
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Updated");
            UpdatejTable2();
            
            username.setText("");
            password.setText("");

        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }

        

        // TODO add your handling code here:
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        String sql="delete from admin where Username=? ";
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn =(Connection) DriverManager.getConnection(DB_URL,USER,PASS);
            pst=conn.prepareStatement(sql);

            pst.setString(1,username.getText() );
            pst.execute();
            JOptionPane.showMessageDialog(null, "Row Deleted");
            username.setText("");
            password.setText("");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }

        UpdatejTable2();

       
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MultiUserChatSystem main=new MultiUserChatSystem();
        main.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int row=jTable2.getSelectedRow();
        username.setText(jTable2.getModel().getValueAt(row,0).toString());
        password.setText(jTable2.getModel().getValueAt(row,1).toString());

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      try{
        Class.forName("com.mysql.jdbc.Driver");
        conn =(Connection) DriverManager.getConnection(DB_URL,USER,PASS);
        UpdatejTable2();
        
        
    }catch(Exception e){
        
    }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
       dispose();
       Maintenance mn=new Maintenance();
       mn.setVisible(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(db_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(db_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(db_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(db_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new db_admin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton save;
    private javax.swing.JButton update;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
