/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 * 
 */
import net.proteanit.sql.DbUtils;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author ziri
 */
public class Maintenance extends javax.swing.JFrame {

   static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";  
   static final String DB_URL = "jdbc:mysql://localhost/example";
    
    //  Database credentials
   static final String USER = "root";
   static final String PASS = "";
   Connection conn=null;
   ResultSet rs=null;
   PreparedStatement pst= null;
   
   public void UpdatejTable1(){
      String sql="select username, password from jdbc_example";
      try{
          Class.forName("com.mysql.jdbc.Driver");
          conn =(Connection) DriverManager.getConnection(DB_URL,USER,PASS);
          pst=conn.prepareStatement(sql);
          rs=pst.executeQuery();
          jTable1.setModel(DbUtils.resultSetToTableModel(rs));
      }catch(Exception e){
          JOptionPane.showMessageDialog(null, e);
      }
      
      
   }
    
   
   
   
    /**
     * Creates new form Maintenance
     */
    public Maintenance() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        save = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        delete1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Users DataBase Maintenance");
        setMaximumSize(new java.awt.Dimension(600, 450));
        setMinimumSize(new java.awt.Dimension(600, 450));
        setPreferredSize(new java.awt.Dimension(600, 450));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 255, 102));
        jLabel1.setText("Username");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 65, -1));

        jLabel2.setBackground(new java.awt.Color(204, 255, 102));
        jLabel2.setText("password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 65, -1));

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 138, -1));
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 138, -1));

        save.setBackground(new java.awt.Color(204, 255, 102));
        save.setText("Save");
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMouseClicked(evt);
            }
        });
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 73, -1));

        update.setBackground(new java.awt.Color(204, 255, 102));
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 73, -1));

        delete.setBackground(new java.awt.Color(204, 255, 102));
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 73, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Username", "password"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 310, 320));

        jButton1.setBackground(new java.awt.Color(204, 255, 102));
        jButton1.setText("main");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 73, -1));

        jLabel5.setBackground(new java.awt.Color(204, 255, 102));
        jLabel5.setText("Users");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 120, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2013-12-05.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 600, 450));

        delete1.setText("Delete");
        delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete1ActionPerformed(evt);
            }
        });
        getContentPane().add(delete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 73, -1));

        jMenu2.setText("     <<     Administrators maintenance");
        jMenu2.setMinimumSize(new java.awt.Dimension(30, 20));
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenu2.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu2MenuSelected(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
       
        String sql="insert into jdbc_example(username, password) values (?,? )";
       try{
           Class.forName("com.mysql.jdbc.Driver");
           conn =(Connection) DriverManager.getConnection(DB_URL,USER,PASS);
           pst=conn.prepareStatement(sql);
           pst.setString(1,username.getText() );
           pst.setString(2,password.getText() );
           pst.execute();
           JOptionPane.showMessageDialog(null, "Saved");
           
           username.setText("");
           password.setText("");
           
       } catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       } // TODO add your handling code here:
       
      UpdatejTable1();
     
    }//GEN-LAST:event_saveActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        String sql="update jdbc_example set password=? where username=? ";
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn =(Connection) DriverManager.getConnection(DB_URL,USER,PASS);
            pst=conn.prepareStatement(sql);
            pst.setString(1,password.getText() );
            pst.setString(2,username.getText() );
                        
            pst.executeUpdate();
             
            JOptionPane.showMessageDialog(null, "Updated");
            UpdatejTable1();
            username.setText("");
            password.setText("");
            
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }

        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_updateActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      
       int row=jTable1.getSelectedRow();
       username.setText(jTable1.getModel().getValueAt(row,0).toString());
       password.setText(jTable1.getModel().getValueAt(row,1).toString());
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
      String sql="delete from jdbc_example where username=? ";
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn =(Connection) DriverManager.getConnection(DB_URL,USER,PASS);
            pst=conn.prepareStatement(sql);
            
            pst.setString(1,username.getText() );
            pst.execute();        
            JOptionPane.showMessageDialog(null, "Row Deleted");   
            username.setText("");
            password.setText("");
        } 
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }

        UpdatejTable1();
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    try{
        Class.forName("com.mysql.jdbc.Driver");
        conn =(Connection) DriverManager.getConnection(DB_URL,USER,PASS);
        UpdatejTable1();
        
        
    }catch(Exception e){
        
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseClicked
       String sql="Select * from jdbc_example where username=? and password=?";
        try{
           Class.forName("com.mysql.jdbc.Driver");
           conn =(Connection) DriverManager.getConnection(DB_URL,USER,PASS);
           pst=conn.prepareStatement(sql);
           pst.setString(1,username.getText() );
           pst.setString(2,password.getText() );
           pst.execute();
           JOptionPane.showMessageDialog(null, "Saved"); 
           
               
       } catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }
        
        
       
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_saveMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       dispose();
       MultiUserChatSystem main=new MultiUserChatSystem();
       main.setVisible(true);
       
       // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
       dispose();
       db_admin mn=new db_admin();
       mn.setVisible(true);
      
      // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu2MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu2MenuSelected
     
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2MenuSelected

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delete1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Maintenance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Maintenance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Maintenance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Maintenance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Maintenance().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton delete;
    public javax.swing.JButton delete1;
    public javax.swing.JButton jButton1;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JMenu jMenu2;
    public javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    public javax.swing.JPasswordField password;
    public javax.swing.JButton save;
    public javax.swing.JButton update;
    public javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
