/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author ziri
 */
public class MultiUserChatSystem extends javax.swing.JFrame {

    /**
     * Creates new form MultiUserChatSytem
     */
    public MultiUserChatSystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        chat = new javax.swing.JButton();
        help = new javax.swing.JButton();
        about = new javax.swing.JButton();
        maintenance = new javax.swing.JButton();
        password_change = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        StartServer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MUTI USER CHAT APPLICATION");
        setBackground(new java.awt.Color(204, 255, 102));
        setMinimumSize(new java.awt.Dimension(600, 450));
        setPreferredSize(new java.awt.Dimension(600, 450));
        getContentPane().setLayout(null);

        chat.setBackground(new java.awt.Color(204, 255, 102));
        chat.setFont(new java.awt.Font("Lucida Calligraphy", 1, 11)); // NOI18N
        chat.setForeground(new java.awt.Color(0,0,0));
        chat.setText("Chat");
        chat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatActionPerformed(evt);
            }
        });
        getContentPane().add(chat);
        chat.setBounds(220, 140, 134, 33);

        help.setBackground(new java.awt.Color(204, 255, 102));
        help.setFont(new java.awt.Font("Lucida Calligraphy", 1, 11)); // NOI18N
        help.setForeground(new java.awt.Color(0,0,0));
        help.setText("Help");
        help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpActionPerformed(evt);
            }
        });
        getContentPane().add(help);
        help.setBounds(220, 190, 134, 31);

        about.setBackground(new java.awt.Color(204, 255, 102));
        about.setFont(new java.awt.Font("Lucida Calligraphy", 1, 11)); // NOI18N
        about.setForeground(new java.awt.Color(0,0,0));
        about.setText("About ");
        about.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        getContentPane().add(about);
        about.setBounds(220, 240, 134, 31);

        maintenance.setBackground(new java.awt.Color(204, 255, 102));
        maintenance.setFont(new java.awt.Font("Lucida Calligraphy", 1, 11)); // NOI18N
        maintenance.setForeground(new java.awt.Color(0,0,0));
        maintenance.setText("Maintenance");
        maintenance.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        maintenance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintenanceActionPerformed(evt);
            }
        });
        getContentPane().add(maintenance);
        maintenance.setBounds(220, 290, 134, 30);

        password_change.setBackground(new java.awt.Color(204, 255, 102));
        password_change.setFont(new java.awt.Font("Lucida Calligraphy", 1, 11)); // NOI18N
        password_change.setForeground(new java.awt.Color(0,0,0));
        password_change.setText("Password Change");
        getContentPane().add(password_change);
        password_change.setBounds(220, 340, 149, 25);
        password_change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_changeActionPerformed(evt);
         }
        });
        
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chatlogo1.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 30, 500, 50);

        StartServer.setBackground(new java.awt.Color(204, 255, 102));
        StartServer.setFont(new java.awt.Font("Lucida Calligraphy", 1, 11)); // NOI18N
        StartServer.setForeground(new java.awt.Color(0,0,0));
        StartServer.setText("Start Server");
        StartServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartServerActionPerformed(evt);
            }
        });
        getContentPane().add(StartServer);
        StartServer.setBounds(220, 90, 134, 31);

        
        
        
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2013-12-05.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(600, 450));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 450);

        pack();
    }// </editor-fold>                        

    private void chatActionPerformed(java.awt.event.ActionEvent evt) {                                     
        dispose();
        Login login= new Login();
        login.setVisible(true);
    
    
    // TODO add your handling code here:
    }                                    

    private void helpActionPerformed(java.awt.event.ActionEvent evt) {                                     
     dispose();
     Help help=new Help();
     help.setVisible(true);
        // TODO add your handling code here:
    }                                    

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {                                      
        dispose();
        About about=new About();
        about.setVisible(true);
        
        // TODO add your handling code here:
    }                                     

    private void maintenanceActionPerformed(java.awt.event.ActionEvent evt) {                                            
        dispose();
        Admin mnt=new Admin();
        mnt.setVisible(true);
       
       // TODO add your handling code here:
    }  
    
    private void password_changeActionPerformed(java.awt.event.ActionEvent evt) {                                                
      dispose();
      Password_change pc=new Password_change();
      pc.setVisible(true);  // TODO add your handling code here:
    }   
    

    private void StartServerActionPerformed(java.awt.event.ActionEvent evt) {                                            
        dispose();
        Administrator admin=new Administrator();
        admin.setVisible(true);
        
        // TODO add your handling code here:
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MultiUserChatSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MultiUserChatSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MultiUserChatSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MultiUserChatSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MultiUserChatSystem().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JButton StartServer;
    private javax.swing.JButton about;
    private javax.swing.JButton chat;
    private javax.swing.JButton help;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton maintenance;
    private javax.swing.JButton password_change;
    // End of variables declaration                   
}
